// <auto-generated />
using LazyLoading.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LazyLoading.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230618112349_migs")]
    partial class migs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LazyLoading.Models.Urunler", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UrunAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Urunsler");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Fiyat = 201m,
                            UrunAdi = "Urun1"
                        },
                        new
                        {
                            ID = 2,
                            Fiyat = 202m,
                            UrunAdi = "Urun2"
                        },
                        new
                        {
                            ID = 3,
                            Fiyat = 203m,
                            UrunAdi = "Urun3"
                        },
                        new
                        {
                            ID = 4,
                            Fiyat = 204m,
                            UrunAdi = "Urun4"
                        },
                        new
                        {
                            ID = 5,
                            Fiyat = 205m,
                            UrunAdi = "Urun5"
                        },
                        new
                        {
                            ID = 6,
                            Fiyat = 206m,
                            UrunAdi = "Urun6"
                        },
                        new
                        {
                            ID = 7,
                            Fiyat = 207m,
                            UrunAdi = "Urun7"
                        },
                        new
                        {
                            ID = 8,
                            Fiyat = 208m,
                            UrunAdi = "Urun8"
                        },
                        new
                        {
                            ID = 9,
                            Fiyat = 209m,
                            UrunAdi = "Urun9"
                        },
                        new
                        {
                            ID = 10,
                            Fiyat = 210m,
                            UrunAdi = "Urun10"
                        },
                        new
                        {
                            ID = 11,
                            Fiyat = 211m,
                            UrunAdi = "Urun11"
                        },
                        new
                        {
                            ID = 12,
                            Fiyat = 212m,
                            UrunAdi = "Urun12"
                        },
                        new
                        {
                            ID = 13,
                            Fiyat = 213m,
                            UrunAdi = "Urun13"
                        },
                        new
                        {
                            ID = 14,
                            Fiyat = 214m,
                            UrunAdi = "Urun14"
                        },
                        new
                        {
                            ID = 15,
                            Fiyat = 215m,
                            UrunAdi = "Urun15"
                        },
                        new
                        {
                            ID = 16,
                            Fiyat = 216m,
                            UrunAdi = "Urun16"
                        },
                        new
                        {
                            ID = 17,
                            Fiyat = 217m,
                            UrunAdi = "Urun17"
                        },
                        new
                        {
                            ID = 18,
                            Fiyat = 218m,
                            UrunAdi = "Urun18"
                        },
                        new
                        {
                            ID = 19,
                            Fiyat = 219m,
                            UrunAdi = "Urun19"
                        },
                        new
                        {
                            ID = 20,
                            Fiyat = 220m,
                            UrunAdi = "Urun20"
                        },
                        new
                        {
                            ID = 21,
                            Fiyat = 221m,
                            UrunAdi = "Urun21"
                        },
                        new
                        {
                            ID = 22,
                            Fiyat = 222m,
                            UrunAdi = "Urun22"
                        },
                        new
                        {
                            ID = 23,
                            Fiyat = 223m,
                            UrunAdi = "Urun23"
                        },
                        new
                        {
                            ID = 24,
                            Fiyat = 224m,
                            UrunAdi = "Urun24"
                        },
                        new
                        {
                            ID = 25,
                            Fiyat = 225m,
                            UrunAdi = "Urun25"
                        },
                        new
                        {
                            ID = 26,
                            Fiyat = 226m,
                            UrunAdi = "Urun26"
                        },
                        new
                        {
                            ID = 27,
                            Fiyat = 227m,
                            UrunAdi = "Urun27"
                        },
                        new
                        {
                            ID = 28,
                            Fiyat = 228m,
                            UrunAdi = "Urun28"
                        },
                        new
                        {
                            ID = 29,
                            Fiyat = 229m,
                            UrunAdi = "Urun29"
                        },
                        new
                        {
                            ID = 30,
                            Fiyat = 230m,
                            UrunAdi = "Urun30"
                        },
                        new
                        {
                            ID = 31,
                            Fiyat = 231m,
                            UrunAdi = "Urun31"
                        },
                        new
                        {
                            ID = 32,
                            Fiyat = 232m,
                            UrunAdi = "Urun32"
                        },
                        new
                        {
                            ID = 33,
                            Fiyat = 233m,
                            UrunAdi = "Urun33"
                        },
                        new
                        {
                            ID = 34,
                            Fiyat = 234m,
                            UrunAdi = "Urun34"
                        },
                        new
                        {
                            ID = 35,
                            Fiyat = 235m,
                            UrunAdi = "Urun35"
                        },
                        new
                        {
                            ID = 36,
                            Fiyat = 236m,
                            UrunAdi = "Urun36"
                        },
                        new
                        {
                            ID = 37,
                            Fiyat = 237m,
                            UrunAdi = "Urun37"
                        },
                        new
                        {
                            ID = 38,
                            Fiyat = 238m,
                            UrunAdi = "Urun38"
                        },
                        new
                        {
                            ID = 39,
                            Fiyat = 239m,
                            UrunAdi = "Urun39"
                        },
                        new
                        {
                            ID = 40,
                            Fiyat = 240m,
                            UrunAdi = "Urun40"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
